### ISSUE TITLE
JSTL issue on Wildfly 11 / JBoss EAP 7.1

### ISSUE THREAD

**Issue by parapunzi** [hdiv/hdiv#94]
Hi,
while testing our app (which worked with JBoss EAP 6.4.x) with hdiv 3.3.0 on JBoss EAP 7.1 I get the following Exception:

> Caused by: java.lang.NoSuchMethodError: org.apache.taglibs.standard.tag.common.core.ImportSupport.isAbsoluteUrl(Ljava/lang/String;)Z
	at org.hdiv.taglibs.standard.tag.common.core.UrlSupportHDIV.resolveUrl(UrlSupportHDIV.java:131)
	at org.hdiv.taglibs.standard.tag.common.core.UrlSupportHDIV.doEndTag(UrlSupportHDIV.java:93)
	at org.apache.jsp.WEB_002dINF.views.jsp.docsearch.model_jsp._jspx_meth_c_005furl_005f0(model_jsp.java:310)

Looks like in newer jstl versions the method isAbsoulteUrl is no longer there:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.taglibs/taglibs-standard-impl/1.2.5/org/apache/taglibs/standard/tag/common/core/ImportSupport.java/

but has moved to the UrlUtil class:
http://grepcode.com/file/repo1.maven.org/maven2/org.apache.taglibs/taglibs-standard-impl/1.2.5/org/apache/taglibs/standard/util/UrlUtil.java

and adding an older jstl to the war doesn't help. I guess you should use a private copy of UrlUtil.java in your 'hdiv-jstl-taglibs-1.2' component...

**Comment by gillarramendi** [comment]
Fixed: https://github.com/hdiv/hdiv/commit/addcc0122655bda7eefaf5408af92224fbb97226

Thank you for opening the issue and for including such a detailed description!

**Comment by seenukarthi** [comment]
Hi When will this fix be released.

**Comment by anderruiz** [comment]
Hi Karthikeyan,

Our bugs are immediately fixed only in our Enterprise Edition. That is why it has not yet been published here (the open source project). The following major or minor release of Hdiv open source, planned within Q3, will include this fix but if you really can't wait, feel free to contact us at contact@hdivsecurity.com.
